# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules =
    [ "ata_piix" "floppy" "sd_mod" "sr_mod" "zfs" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "kvm-intel" "vfio-pci" ];
  boot.blacklistedKernelModules = [ "nouveau" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "rpool/root/boot";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rpool/root/home";
    fsType = "zfs";
  };
  
  fileSystems."var/cache/netdata" = {
    device = "rpool/root/netdata";
    fstype = "zfs";
  };

  fileSystems."/nix" = {
    device = "rpool/nix";
    fsType = "zfs";
  };

  swapDevices = [{ device = "/dev/md127"; }];

  nix.maxJobs = lib.mkDefault 2;
  # hardware.cpu.intel.updateMicrocode = true;
  # hardware.cpu.amd.updateMicrocode = true;
  # hardware.enableRedistributableFirmware = true;
  # virtualisation.hypervGuest.enable = true;
}
